config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'posts#index'
  get '/home', to: 'posts#landingpage'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  get '/sendemail/:id', to: 'posts#send_email', as: 'email'
  resources :posts
  resources :transactions
  resources :comments
end

app/views/layouts/shared/_stripe_form.html.erb
<%= form_tag transactions_path do %>


  <div id="error_explanation">
    <% if flash[:error].present? %>
      <p><%= flash[:error] %></p>
    <% end %>
  </div>


  <div class="card text-center w-100">
    <div class="card-header">
      <h3>Donate</h3>
    </div>
    <div class="card-body"
    >
      <article>
          <h5 class="card-title"><%= label_tag(:amount, 'Amount') %></h5>
          <p class="card-text"><%= text_field_tag(:amount) %></p>
          <br>
      </article>
      <article>
        <%= hidden_field_tag(:stripeToken) %>
      </article>


   <button id='donateButton' class= "btn btn-warning btn-lg">Donate</button>
    </div>

  </div>

<% end %>




  




<script src="https://checkout.stripe.com/checkout.js"></script>

<script>
var handler = StripeCheckout.configure({
  key: '<%= Rails.configuration.stripe[:publishable_key] %>',
  locale: 'auto',
  name: 'One-time donation ',
  description: 'To the Author of this Listing',

  token: function(token) {
    $('input#stripeToken').val(token.id);
    $('form').submit();
  }
});

$('#donateButton').on('click', function(e) {
  e.preventDefault();

  $('#error_explanation').html('');

  var amount = $('input#amount').val();
  amount = amount.replace(/\$/g, '').replace(/\,/g, '')

  amount = parseFloat(amount);

  if (isNaN(amount)) {
    $('#error_explanation').html('<p>Please enter a valid amount in USD ($).</p>');
  }
  else if (amount < 5.00) {
    $('#error_explanation').html('<p>Donation amount must be at least $5.</p>');
  }
  else {
    amount = amount * 100; // Needs to be an integer!
    handler.open({
      amount: Math.round(amount)
    })
  }
});

// Close Checkout on page navigation
$(window).on('popstate', function() {
  handler.close();
});

</script>