config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'posts#index'
  get '/home', to: 'posts#landingpage'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  get '/sendemail/:id', to: 'posts#send_email', as: 'email'
  resources :posts
  resources :transactions
  resources :comments
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  # Associations 
  belongs_to :user
  belongs_to :category
  has_one_attached :image
  has_many :comments, dependent: :destroy

  # Operations
  before_save :set_coords
  private

  # Function for this model that converts the inputed location from an address to latititude and longitude to then be used by the google API in order to make a marker on the posts page
  def set_coords
  
    results = Geocoder.search(self.address)
    location = results.first.coordinates  # grabbing the first set of lat long
    self.longitude = location[1]
    self.latitude = location[0] # setting for post
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  load_and_authorize_resource
  def index
    # ordering posts by desencending order, newest will be displayed atop old
    @posts = Post.all.order('created_at DESC')
    # this is our filtering feature
    # when a button is clicked it passes in the respected param into and sets at the category
    # then we iterate over all the posts and display only the posts that have the same category_id as the :category
    if params[:category]
      category = params[:category]
      @posts = @posts.select do |post|
        category == Category.find(post.category_id).name
      end
    end
  end

  def new
    @post = Post.new
  end

  def filter; end

  def create
    # creates a new post with the data passed into the form
    @post = Post.new(post_params)
    # using the geocoder gem which uses the google api in order to translate a entered address (string) into a latitude longitude, latitude, longitude is extracted and set to the variable location.
    results = Geocoder.search(post_params[:address])
    location = results.first.coordinates
    # category is set from selection
    category = Category.find_by(name: params[:category])
    @post.category = category
    # user_id attribute of post is set to that of the current user
    @post.user_id = current_user.id
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.all
    # @comment = @post.comments.build
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to root_path
  end

  def send_email
    # sending an email to the author of the post
    @user = current_user
    @postuser = User.find(@post.user_id)
    # using mailer with our instance variables we have set above
    UserMailer.with(user: @user, postuser: @postuser, post: @post).interested_in_post_email.deliver_now
    redirect_to posts_path
  end

  def landingpage; end

  private

  def post_params
    params.require(:post).permit(:title, :content, :image, :address)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<div class="user-edit-page">
  <div class="editleft">
  </div>
  
 <div class="editright">
  <%= form_for @post, url: post_path(@post) ,html: {class: "edit-form"}, :action => "update" do |f| %>
      <h4><%= f.label :title %></h4>
      <%= f.text_area :title, size: "30x2", class: 'text-area text-center', placeholder: "write until your hearts" %>
      <br>

      
      <%= f.text_area :title, size: "30x2" %>
<hr>
      <%= f.label :content, 'Content' %>
      <br>
      <h4><%= f.label :content, 'Content' %></h4>
      <%= f.text_area :content, size: "50x10", class: 'text-area text-center', placeholder: "write until your hearts" %>
      <br>
      <%= f.text_area :summary, size: "50x7" %>
      <br>
      <%= f.text_area :address, size: "20x2" %>
      <%= f.label :location %>
        <br>
      <%= f.label :category %>
      <%= select_tag "category", options_for_select(Category.all.collect{ |u| [u.name] }) %>
      <br>
      <label class="btn btn-outline-secondary">
    Upload image
    <span style="display:none;">
      <%= f.file_field :image, class: "btn btn-outline-secondary" %>
    </span>
  
  </label>
    <%= f.file_field :image %>
      <%= f.submit 'Update', class: 'btn btn-outline-success' %>
      <% end %>
      <br>
      <%= link_to "Back", root_path, class: "btn btn-outline-secondary" %>
      <br>
      <br>

    </div>
  </div>

app/views/posts/index.html.erb
  <% if user_signed_in? %>
    <div class="postlogin">
    <nav>
      <div class="navlogo"><img src="https://i.imgur.com/9KMbz0q.png" alt=""></div>
      <ul>
        <li> <%= link_to 'Posts', root_path%></li>
        <li><%= link_to 'Profile', edit_user_registration_path%></li>
        <li><%= link_to 'Log out', destroy_user_session_path, method: :delete%></li>
      </ul>
    </nav>


<div class="user-post-page">
  <div class="postleft">
  <br>
      <form class="filter-nav">
      <%= link_to "Ruby", posts_path(category: "ruby"), class: "btn btn-outline-success" %>
      <%= link_to "Java", posts_path(category: "java"), class: "btn btn-outline-success" %>
      <%= link_to "HTML", posts_path(category: "HTML"), class: "btn btn-outline-success" %>
      <%= link_to "CSS", posts_path(category: "CSS"), class: "btn btn-outline-success" %>
      <%= link_to "Python", posts_path(category: "python"), class: "btn btn-outline-success" %>
      <%= link_to "JavaScript", posts_path(category: "JavaScript"), class: "btn btn-outline-success" %>
      <%= link_to "Fortran", posts_path(category: "Fortran"), class: "btn btn-outline-success" %>
      </form>  
  </div>
  
 <div class="postright">
     <div class="container">
     <br>

      <%= link_to 'Create', new_post_path, class: "btn btn-primary create" %>
 
      <% @posts.each do |post| %>
      <br>
      <br>
      <div class="card">
      <h5 class="card-header"><%= post.title %></h5>
      <div class="card-body"><%= image_tag(post.user.avatar.service_url, size: "150x150") if post.user.avatar.attached? %>
        <h5 class="card-title"><%= post.category.name %></h5>
        <p class="card-text"><%= post.summary %></p>
          <%= link_to 'Show', post, class: "btn btn-primary" %>
      </div>
      </div>
      <%end%>
    </div>


</div>
 </div>
   
  <% else %>

  <div class="landingbody">
    <div class="landingwrapper">
      <nav>
      <div class="navlogo"><img src="https://i.imgur.com/9KMbz0q.png" alt=""></div>
    </nav>
      <div class="landingheader">
        <h1>Teaching 2 Learn</h1>
        <br>  
        <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Knowledge Shared is Power Multiplied</p>
        <p class ="quote">- Robert Noyce</p>
      </div>
    <section class="landingsec">
      <%= link_to 'Register', new_user_registration_path, class: "landingpagebutton2"%>    
      <%= link_to 'Log In', new_user_session_path, class: "landingpagebutton1" %>
    </section>
    <section class="landingcontent">
   <p>Technology has revolutionized modern society, we are in an era where you can control the temperature of your cooking from anywhere your smartphone has a connection, to having a voice controlled AI turning on household appliances. A decade ago, self-driving cars were merely a dream. Today they are being created and tested by leading car manufacturers around the world. 
With all these advances in technology lay the visionaries behind these fascinating tools. Coders.
Coding is impacting the future of technology and the future of our lives in ways we are only just beginning to understand.
As we are in the midst of a transitioning to a fully digital world many people are intrigued by the the wonders that allow technology to work.
This is where ‘Teaching2Learn’ comes in.
</p>
<br> 
<p>The internet has created an ease of access to the insight of the world, free knowledge of anything you are interested is but a click away. With all this knowledge, many people have began to research and study their passion, for us it’s coding.
Self-learning is very different to attending school. There is no one around you when you are coding. There are no classmates, there are no social interactions, you cannot find that “grand ceremony” waiting for you at the end of the tunnel. Most of the time you do it alone. And most of the time, you are alone.
Coding is not a simple task to learn. It is mentally taxing and there are times you find yourself copy pasting snippets of code but have no understanding to the intricacies of why it works.
‘Teaching 2 Learn’ solves many if not all of these issues that people come across.
We provide a free peer to peer learning network, creating a fantastic atmosphere where the student receives more time for individualized learning, a direct interaction which promotes active learning while the peer teacher reinforces their own learning by instructing others.</p>
    </section>
    </div>
  </div>  
  <% end %>

app/views/posts/new.html.erb
<div class="position-relative overflow-hidden  text-center bg-light">
  <div class="mx-auto">
  <br>
        <% if user_signed_in? %>
        <%= form_for @post, url: posts_path(@post) ,html: {class: "edit-form"}, :action => "create" do |f| %>
        <h4><%= f.label :title %></h4>
        <%= f.text_area :title, size: "50x2", class: 'text-area text-center', placeholder: "enter a relevant title" %>
        <br>
        <br>
        <h4><%= f.label :content, 'Content' %></h4>
        <%= f.text_area :content, size: "50x10", class: 'text-area text-center', placeholder: "write until your hearts content"  %>
        <br>
        <br>
        <h4><%= f.label :summary, 'Summary' %></h4>
        <%= f.text_area :summary, size: "50x5", class: 'text-area text-center', placeholder: "summarize your hearts content"  %>
        <br>
        <br>
        <h4><%= f.label :category %></h4>
        <%= select_tag "category", options_for_select(Category.all.collect{ |u| [u.name] }) %>
        <br>
        <br>
        <h4><%= f.label :location %></h4>
        <%= f.text_area :address, size: "50x2", class: 'text-area text-center', placeholder: "Enter an address or general location, we'll do the rest"  %>
        <hr>
        <br>
        <br>
        <div><%= f.file_field :image %></div>
        <hr>
        <%= f.submit 'Create', class: 'btn btn-primary ' %>
        <br>
        <br>
        <% end %>
      <% else %>
        <h1 class="edit-form">Please sign in </h1>
      <% end %>
    </div>
  </div>

app/views/posts/show.html.erb
<% provide :head_tags do %>
  <meta name='turbolinks-visit-control' content='reload'>
  <script>
    document.addEventListener("DOMContentLoaded", function(){
      initMap(<%=@post.latitude%>, <%=@post.longitude%>)
    });
  </script>
<% end  %>


<div class="container-fluid post-show-container" style="background: #fff7d3;">
  <div class="jumbotron " style="background: white;">
    <h1 class="text-center" style="background: $orange;"><%=@post.title%></h1>
  <br>
    <div class="card w-100" style="background: #fff7d3;">
        <div class="card-body">
          <div class="d-flex flex-row">
            <div class="p-2">
                <%= image_tag(@post.user.avatar.service_url , size: "150x150") if @post.user.avatar.attached? %>
            </div>
            <div class="p-2">
              <h5 class="card-title">
              <%=@post.user.username%>
              </h5>
                <hr>
              <p class="card-text">Author: <%=@post.user.firstname%> | <%=@post.user.lastname%> </p>
              <p>posted: <%=@post.created_at%> </p>
            </div>
          </div>
        </div>
    </div>

    <hr class="my-4">
    <p><%=@post.content%></p>
    <div class="text-center">
       <%= image_tag(@post.image.service_url) if @post.image.attached? %>
    </div>
   

    <% if can? :update, @post %>
    <%= link_to "edit", edit_post_path(@post.id), class: "btn btn-primary" %> |
    <% end %>

    <% if can? :destroy, @post %>
    <%= link_to "delete", post_path(@post.id), method: :delete, class: "btn btn-danger"  %>
    <% end %>

<div>
<hr>
<div class="text-center p-5">
<p>If you are interest in getting into contact with the person conduction this lesson send them an email <%= link_to "email", email_path(@post), class: "btn btn-success"  %></p>

</div>

    <div class="d-flex justify-content-center">
      <div id="map"></div>
    </div>
</div>
</div>

<div class="center-the-card">
  <div class="card-to-center">
    <%= render 'layouts/shared/stripe_form' %>
  </div>
</div>
<br>

  
<div class="center-the-card">
  <div class="card-to-center">
    <div class="card w-100">
      <div class="card-header text-center">
        <h4>Comments</h4>
      </div>
     <div class="card-body">
    <h3><% @comments.each do |comments| %> </h3> 


        <div class="card-body">
          <div class="d-flex flex-row">
            <div>
              <p><%= comments.comment %> </p>
              <h5><%= comments.user.username %></h5>
              <p>posted: <%=comments.created_at%> </p>
          </div>
        </div>
          <% if can? :update, @post %>
          <%= link_to "edit", edit_comment_path(comments.id), class: "btn btn-primary" %> 
          <% end %>

          <% if can? :destroy, @post %>
          <%= link_to "delete", comment_path(comments.id), method: :delete, class: "btn btn-danger"  %>
          <% end %>
          <hr>
        </div>
        <% end %>


  <%= form_for @comment, url: comments_path ,html: {class: "edit-form"}, :action => "create" do |f| %>

  <div class="card text-center w-100">
    <div class="card-body">
      <article>
          <h5 class="card-title"><%= f.label "Leave a comment" %></h5>
          <p class="card-text"><%= f.text_area :comment, class: "text-area", size: "50x5"%></p>
          <br>
      </article>
        <%= f.hidden_field(:post_id, :value => @post.id )%>
        <%= f.submit 'Create', class: 'btn btn-warning btn-lg' %>
    </div>
  </div>
   <% end %>
       

            
           
           
     



      </div>
    </div>
  </div>
</div>




  


    

  </div>


<br>